### ISSUE TITLE
Error running ./dt_install_linux_bluez.sh

### ISSUE THREAD

**Issue by GMaynard1** [LowellInstruments/ddt#1]
on the last step "configuring and building bluez" I got the error

```
configure: error: GLib >= 2.28 is required
./configure TRAPPED! rv 1
```

**Comment by GMaynard1** [comment]
manually installed glib using

```
sudo apt-get install glib2.0
```
removed all bluez related files and re-ran the install_linux_bluez script. Hit another error 

``` 
checking for dbus-1 >= 1.6... no
configure: error: D-Bus >= 1.6 is required
./configure TRAPPED! rv 1
```

**Comment by GMaynard1** [comment]
installed dbus using
```
sudo apt-get install libdbus-1-dev
```
and rebooted the machine. Re ran the installing and got an error

```
checking for libudev >= 172... no
configure: error: libudev >= 172 is required
./configure TRAPPED! rv 1
```
followed [this old post](http://rrbluetoothx.blogspot.com/2016/04/rr-bluetooth-compile-bluez-539.html) and was able to get bluez to compile

**Comment by kazola** [comment]
All this should be solved now by running ./dt_install_linux.sh before the bluez script
